apiVersion : apps/v1
kind: Deployment
metadata:
  name: "pythonbootcamp01-ce6b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "pythonbootcamp01-ce6b"
  template:
    metadata:
      labels:
        app: "pythonbootcamp01-ce6b"
    spec:
      containers:
        - name: "pythonbootcamp01-ce6b"
          image: "python85.azurecr.io/pythonbootcamp01"
          ports:
          - containerPort: 80